@startuml classes_enemy
set namespaceSeparator none
class "Login" as login.Login {
  database_path
  authenticate(username, password)
  create_database()
  register_user(username, password)
}
@enduml
